-- if vim.g.neovide then
--     local function set_ime(args)
--         if args.event:match("Enter$") then
--             vim.g.neovide_input_ime = true
--         else
--             vim.g.neovide_input_ime = false
--         end
--     end
--
--     local ime_input = vim.api.nvim_create_augroup("ime_input", { clear = true })
--     vim.api.nvim_create_autocmd({ "InsertEnter", "InsertLeave" }, {
--         group = ime_input,
--         pattern = "*",
--         callback = set_ime
--     })
--     vim.api.nvim_create_autocmd({ "CmdlineEnter", "CmdlineLeave" }, {
--         group = ime_input,
--         pattern = "[/\\?]",
--         callback = set_ime
--     })
--
--     vim.keymap.set("n", "<C-->", function()
--         vim.g.neovide_scale_factor = vim.g.neovide_scale_factor - 0.1
--     end)
--     vim.keymap.set("n", "<C-=>", function()
--         vim.g.neovide_scale_factor = vim.g.neovide_scale_factor + 0.1
--     end)
--     vim.keymap.set("n", "<C-0>", function()
--         vim.g.neovide_scale_factor = 1.1
--     end)
--     vim.keymap.set("n", "<leader>-", function()
--         vim.g.neovide_opacity = vim.g.neovide_opacity - 0.1
--     end)
--     vim.keymap.set("n", "<leader>=", function()
--         vim.g.neovide_opacity = vim.g.neovide_opacity + 0.1
--     end)
--     vim.keymap.set("n", "<leader>0", function()
--         vim.g.neovide_opacity = 1.0
--     end)
--
--     vim.env.GIT_EDITOR = 'nvr --remote-wait'
-- end
